In [1]:
import pandas as pd
import numpy as np
#from arif_asif2  import get_acc_fpr_sen

In [2]:
from sklearn.metrics import confusion_matrix
def get_acc_fpr_sen(df,clf):
    print("init")
    start_from = int(len(df)*.2)
    test_df = df.iloc[start_from :,:]
    #normal
    is_normal = test_df["target"] == 0
    normal_df = test_df[is_normal] 
    #intru 
    is_intru   =  test_df["target"] == 1
    
    intru_df   =  test_df[is_intru]
    hi =  len(normal_df.columns) - 1
    lo =  0
    normal_pred = clf.predict(normal_df.iloc[:,lo:hi])
    real_normal  = normal_df.iloc[:,hi]
    
    
    real = list(real_normal)
    pred = list(normal_pred)
    tn, fp, fn, tp = confusion_matrix(real,pred).ravel()
    print(tn)
    print(fp)
    print(fn)
    print(tp)
    
    print(confusion_matrix(real,pred))
    
    acc   = (tp+tn)*100 / (tn+fp+fn+tp)
    try :
        sens = (tp * 100)  / (tp+fn) 
    except :
        sens = 0 
    fpr   =  (fp*100) / (fp +tn)
    normal = [sens,acc,fpr]
    #print("sens = {} , acc =  {}  , fpr = {} ".format(sens,acc,fpr))
    print("tn = {} , tp =  {}  , fn = {} , fp = {} ".format(tn,tp,fn,fp))
    hi =  len(intru_df.columns) - 1
    lo =  0
    intru_pred = clf.predict(intru_df.iloc[:,lo:hi])
    real_intru  = intru_df.iloc[:,hi]
    
    real = list(real_intru)
    pred = list(intru_pred)
    tn, fp, fn, tp = confusion_matrix(real,pred).ravel()
#     return confusion_matrix(real,pred).ravel()
    acc   = (tp+tn)*100 / (tn+fp+fn+tp)
    try :
        sens = (tp * 100)  / (tp+fn) 
    except :
        sens = 0 
    fpr   =  (fp*100) / (fp +tn)
    intru  =   [sens,acc,fpr] 
    #print("sens = {} , acc =  {}  , fpr = {} ".format(sens,acc,fpr))
    print("tn = {} , tp =  {}  , fn = {} , fp = {} ".format(tn,tp,fn,fp))
    return (normal,intru)
#     return "acc = {} , sens =  {}  , fpr =  {} hello".format(acc,sens,fpr)
#     pass

In [3]:
train_df = pd.read_csv("final.csv", index_col=0)
train_df.head(5)

,col2,col3,col12,col23,col24,col27,col28,col29,col31,col32,col33,col34,col36,col40,col41,col42
0,2,43,0,1,1,0.0,0.0,1.0,0.0,255,254,1.0,0.00,0.0,0.0,0
1,2,43,0,1,1,0.0,0.0,1.0,0.0,255,254,1.0,0.00,0.0,0.0,0
2,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.0,0.00,0.0,0.0,1
3,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.0,0.01,0.0,0.0,1
4,2,43,0,2,2,0.0,0.0,1.0,0.0,255,255,1.0,0.01,0.0,0.0,1

In [5]:
import pandas as pd
from sklearn import preprocessing

dataDf = pd.read_csv("final.csv", index_col=0)
#Categorical Column label Encoding 
def labelEncodingVal(dataDF, column_ID):
    from sklearn import preprocessing
    columns = dataDF.columns
    unique_val = dataDf[columns[column_ID]].unique()
    le = preprocessing.LabelEncoder()
    dataDF[columns[column_ID]]=le.fit_transform(dataDf[columns[column_ID]])
    return unique_val, dataDF
dataDf.head(10)

TypeError: read_csv() got an unexpected keyword argument 'index'

In [3]:
unique_val, processed_df = labelEncodingVal(dataDf, 'target')
processed_df.head(5)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [6]:
def columnChanger(df,column_ID,convertionCheckValue, appendAccordingCheckValue, appendElseCheckValue):
    columns = df.columns
    classColumn = df[columns[column_ID]].to_list()
    #convertionCheckValue = int(convertionCheckValue)
    f_classColumn = []
    #print(classColumn)
    for i in classColumn:
        if(i==convertionCheckValue):
            f_classColumn.append(appendAccordingCheckValue)
        else:
            f_classColumn.append(appendElseCheckValue)
    #f_classCol = np.array(f_classColumn, dtype=np.int32)
    df.drop(columns[column_ID], axis = 1, inplace = True)
    df[columns[column_ID]] = f_classColumn
    return df

In [7]:
def metricesCalculation(y_test, pred):
    tn, fp, fn, tp = confusion_matrix(y_test,pred).ravel()
    acc   = (tp+tn)*100 / (tn+fp+fn+tp)
    sens = (tp * 100)  / (tp+fn)
    fpr   =  (fp*100) / (fp +tn)
    return acc,sens,fpr

#print("sens = {} , acc =  {}  , fpr = {} ".format(sens,acc,fpr))

In [8]:
train_df = columnChanger(train_df,15, 0,"N","A")
train_df.head(10)

,col2,col3,col12,col23,col24,col27,col28,col29,col31,col32,col33,col34,col36,col40,col41,col42
0,2,43,0,1,1,0.0,0.0,1.0,0.0,255,254,1.00,0.00,0.0,0.0,N
1,2,43,0,1,1,0.0,0.0,1.0,0.0,255,254,1.00,0.00,0.0,0.0,N
2,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.00,0.00,0.0,0.0,A
3,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.00,0.01,0.0,0.0,A
4,2,43,0,2,2,0.0,0.0,1.0,0.0,255,255,1.00,0.01,0.0,0.0,A
5,2,55,0,2,1,0.0,0.0,0.5,0.0,10,3,0.30,0.30,0.0,0.0,N
6,2,43,0,1,1,0.0,0.0,1.0,0.0,255,253,0.99,0.00,0.0,0.0,N
7,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.00,0.00,0.0,0.0,A
8,3,54,1,4,4,0.0,0.0,1.0,0.0,71,255,1.00,0.01,0.0,0.0,N
9,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.00,0.00,0.0,0.0,A

In [9]:
attack_train_df = columnChanger(train_df,15,"A",1,0)
attack_train_df.head(5)

,col2,col3,col12,col23,col24,col27,col28,col29,col31,col32,col33,col34,col36,col40,col41,col42
0,2,43,0,1,1,0.0,0.0,1.0,0.0,255,254,1.0,0.00,0.0,0.0,0
1,2,43,0,1,1,0.0,0.0,1.0,0.0,255,254,1.0,0.00,0.0,0.0,0
2,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.0,0.00,0.0,0.0,1
3,2,43,0,2,2,0.0,0.0,1.0,0.0,255,254,1.0,0.01,0.0,0.0,1
4,2,43,0,2,2,0.0,0.0,1.0,0.0,255,255,1.0,0.01,0.0,0.0,1

In [10]:
attack_test_df = columnChanger(test_df,15,"anomaly",1,0)
attack_test_df.head(5)

,'protocol_type','service','logged_in','count','srv_count','rerror_rate','srv_rerror_rate','same_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate','dst_host_same_src_port_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','class'
0,1,45,0,229,10,1.0,1.0,0.04,0.00,255,10,0.04,0.00,1.00,1.00,1
1,1,45,0,136,1,1.0,1.0,0.01,0.00,255,1,0.00,0.00,1.00,1.00,1
2,1,19,0,1,1,0.0,0.0,1.00,0.00,134,86,0.61,0.61,0.00,0.00,0
3,0,13,0,1,65,0.0,0.0,1.00,1.00,3,57,1.00,1.00,0.00,0.00,1
4,1,55,0,1,8,1.0,0.5,1.00,0.75,29,86,0.31,0.03,0.83,0.71,1

In [11]:
def spliter(df):
    hi = len(df.columns) -1
    lo = 0 
    x = df.iloc[   :  ,   lo :  hi]
    y = df.iloc[   :  ,   hi] # target
    return x,y

In [12]:
#For Attack 
attack_train_x, attack_train_y = spliter(train_df)
    attack_test_x, attack_test_y = spliter(test_df)
print(len(attack_train_x), len(attack_test_x))

311028 22544

In [13]:
from sklearn.ensemble import RandomForestClassifier
clf_n = RandomForestClassifier(n_estimators=20, random_state=0)
clf_n.fit(attack_train_x, attack_train_y)
pred_attack = clf_n.predict(attack_test_x)

In [14]:
#confusion matrix for attack
conf_a = confusion_matrix(attack_test_y,pred_attack)
print(conf_a)

[[ 5441  4270]
 [ 2311 10522]]

In [15]:
a_acc, a_sens, a_fpr = metricesCalculation(attack_test_y,pred_attack)
print(a_acc, a_sens, a_fpr)

70.80819730305181 81.99174004519598 43.970754814128306

In [16]:
from sklearn.neural_network import MLPClassifier
clf_a_MLP = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(5, 2),max_iter = 1000, random_state=1)

clf_a_MLP.fit(attack_train_x, attack_train_y)
pred_attack_MLP = clf_a_MLP.predict(attack_test_x)

In [17]:
#confusion matrix for attack_mlp
conf_a_MLP = confusion_matrix(attack_test_y,pred_attack_MLP)
print(conf_a_MLP)

[[ 4447  5264]
 [ 1581 11252]]

In [18]:
a_MLP_acc, a_MLP_sens, a_MLP_fpr = metricesCalculation(attack_test_y,pred_attack_MLP)
print(a_MLP_acc, a_MLP_sens, a_MLP_fpr)

69.63715400993613 87.68019948570092 54.20656986922047